(+) Add Dockerfile linter
libercapital/liber-public-containers pull request #1
Opened 2020-12-23 19:50 UTC by joseliber

This PR adds a Github Action for Hadolint.

2020-12-24 14:57 UTC, seocam commented on rabbitmq/Dockerfile
> +##################################
My idea was that the build would where we can add any plugins we need in our rabbitmq instances.

2020-12-24 15:00 UTC, seocam commented on rabbitmq/enabled_plugins
> +[rabbitmq_management,rabbitmq_prometheus,rabbitmq_auth_mechanism_ssl,rabbitmq_message_timestamp].
I was leaving that to the deployment. My idea was to ship the container with plugins available but each deployments decide which plugins needs to be enabled. Is that a bad idea?

2020-12-24 15:13 UTC, seocam commented on rabbitmq/Dockerfile
> +COPY --from=builder --chown=rabbitmq:rabbitmq rabbitmq_message_timestamp-3.8.0.ez /plugins/
:+1: 
I missed the the owner thanks :slightly_smiling_face:

2020-12-24 15:14 UTC, seocam commented on rabbitmq/Dockerfile
> +# hadolint ignore=DL3008,DL3015
I wouldn't suppress DL3015.

2020-12-24 15:15 UTC, seocam commented on rabbitmq/Dockerfile
> +# hadolint ignore=DL3008,DL3015
I would add the DL3008 in the ignore list in the config file. We are using debian with stable repos only. We do want to use the latest version of the packaged offered by the distro.

2020-12-24 15:16 UTC, seocam requested changes
See comments

2020-12-24 15:17 UTC, seocam commented on rabbitmq/Dockerfile
> +RUN wget --quiet "https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/download/v3.8.0/rabbitmq_message_timestamp-3.8.0.ez" && \
We are updating the plugin version in a PR which the title is related to linters. Are you trying to sneak in changes? :grimacing:

2021-01-07 11:51 UTC, joseliber commented on rabbitmq/Dockerfile
> +##################################
Please check 96b1579
Did I understand it correctly?

2021-01-07 11:55 UTC, joseliber commented on rabbitmq/enabled_plugins
> +[rabbitmq_management,rabbitmq_prometheus,rabbitmq_auth_mechanism_ssl,rabbitmq_message_timestamp].
So when deploying we need to bind mount the `enabled_plugins` file? Or rebuild the container locally?
I thought that this container was going to be used for EDI only, but then we don't have definitions.json here as well...

I have removed that in 624f685

2021-01-07 11:55 UTC, joseliber commented on rabbitmq/Dockerfile
> +COPY --from=builder --chown=rabbitmq:rabbitmq rabbitmq_message_timestamp-3.8.0.ez /plugins/
yw

2021-01-07 12:04 UTC, joseliber commented on rabbitmq/Dockerfile
> +# hadolint ignore=DL3008,DL3015
a378259 unsupressed

2021-01-07 12:17 UTC, joseliber commented on rabbitmq/Dockerfile
> +# hadolint ignore=DL3008,DL3015
Changed in e86c806 please check.

2021-01-07 12:18 UTC, joseliber commented on rabbitmq/Dockerfile
> +RUN wget --quiet "https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/download/v3.8.0/rabbitmq_message_timestamp-3.8.0.ez" && \
I'd prefer to keep PRs into a closed scope, but I couldn't resist.

Do we have an "official" guideline for our company regarding this?
It would help a lot when I'm doing the reviews as well.

2021-01-07 12:42 UTC, seocam commented on rabbitmq/enabled_plugins
> +[rabbitmq_management,rabbitmq_prometheus,rabbitmq_auth_mechanism_ssl,rabbitmq_message_timestamp].
Exactly. When deploying we need to mount that directory. Does that sound ok?

2021-01-07 12:43 UTC, seocam commented on rabbitmq/Dockerfile
> +RUN wget --quiet "https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/download/v3.8.0/rabbitmq_message_timestamp-3.8.0.ez" && \
We don't have a guideline regarding that but I think the PR reviewers could pay attention on it :)
If we have a separate commit for that I'm ok with keeping it in the PR.

2021-01-14 12:00 UTC, joseliber commented on rabbitmq/Dockerfile
> +RUN wget --quiet "https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/download/v3.8.0/rabbitmq_message_timestamp-3.8.0.ez" && \
I can do that after approval to rebase the fixups. Is that ok?

2021-01-15 18:24 UTC, seocam commented
@joseliber looks good for rebase.

2021-02-12 18:19 UTC, seocam commented
Good for rebase @joseliber

2021-02-12 18:20 UTC, seocam commented
Sorry got confused with the repos! I believe we  can close this now ;)

2021-02-12 19:55 UTC, joseliber commented
I'll close the PR and the repo after I've moved this change to the new rabbitmq repo.

2021-02-26 19:09 UTC, joseliber commented
Dropping this

2021-02-26 19:09 UTC, closed without merging